### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by fgallese** [jaxxstorm/connecti#45]
This seems like a tool that can solve some issues our team has accessing private services in GCP.

How can I run it under Linux ?

**Comment by jaxxstorm** [comment]
@fgallese thanks for trying out `connecti` !

`connecti` is a go binary, so you can simply download the binary from the releases page: https://github.com/jaxxstorm/connecti/releases/tag/v0.0.3

it has a few dependencies, which can be read from the readme: https://github.com/jaxxstorm/connecti

**Comment by fgallese** [comment]
Thank you, and sorry for the dumb question, didn't even check.. only read the readme. Will be testing it out.
